<MyGridLayout>

    name_list_input:name_list_input

    GridLayout:
        cols:1
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Входной массив имен"

            TextInput:
                id: name_list_input
                multiline: False
        
        Button:
            text: "Генерировать"
            font_size: 32
            on_press: root.press()
